In [ ]:
#задание 1
"""Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))."""

In [26]:
import numpy as np
a=np.arange(0,10)
np.flipud(a)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
#задание 2
"""Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали."""

In [27]:
z = np.diag(np.arange(9), k=0)
total_sum = 0
print(z)

for i in range(len(z)):
    total_sum += z[i][i]
print(total_sum)

[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 5 0 0 0]
 [0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 0 8]]
36


In [ ]:
#задание 3
"""Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3"""

In [28]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [29]:
from numpy import linalg

In [30]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [31]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True